# PostgreSQL. Versions 8.2 and up are supported.
development:
  adapter: postgresql
  encoding: unicode
  database: till_beslut_development
  pool: 5
  username: till_beslut
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: till_beslut_test
  pool: 5
  username: till_beslut
  password:
